name: Deploy the frontend

on:
  push:
    branches: [ production ]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: frontend-deploy

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - name: Checking out the repository
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Installing the project
      run: npm ci
      
    - name: Testing the project
      run: npm test
    
    - name: Building the project
      run: npm run build --if-present
    
    - name: Reloading the PM2 job
      run: pm2 reload arkoi-frontend
