name: Integrate the frontend

on:
  pull_request:
    branches: [ production ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: frontend-integrate

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - name: Checking out the repository
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Installing all libraries
      run: npm ci
    
    - name: Checking for tests
      run: npm test
    
    - name: Building the project
      run: npm run build --if-present
